version: '3.4'
services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:7.0.2
    networks:
      - cdp-tenant
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    restart: always

  waste-obligations-wiremock:
    image: sheyenrath/wiremock.net:latest
    pull_policy: always
    environment:
      TZ: Europe/London
    ports:
      - '9090:80'
    networks:
      - cdp-tenant

  ################################################################################

  waste-obligations-frontend:
    build: ./
    ports:
      - '3000:3000'
    links:
      - 'localstack:localstack'
      - 'redis:redis'
    depends_on:
      localstack:
        condition: service_healthy
      redis:
        condition: service_started
      waste-obligations:
        condition: service_healthy
      waste-obligations-wiremock:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      LOCALSTACK_ENDPOINT: http://localstack:4566
      USE_SINGLE_INSTANCE_CACHE: true
      WASTE_OBLIGATIONS_API_BASE_URL: http://waste-obligations:8080
      WASTE_ORGANISATIONS_API_BASE_URL: http://waste-obligations-wiremock
    networks:
      - cdp-tenant

  waste-obligations:
    image: defradigital/waste-obligations:${WASTE_OBLIGATIONS_VERSION:-latest}
    depends_on:
      mongodb:
        condition: service_started
      waste-obligations-wiremock:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Mongo__DatabaseUri: mongodb://mongodb:27017/
      PORT: 8080
      AWS_EMF_ENABLED: false
      AWS_EMF_ENVIRONMENT: Local
      PrnCommonBackend__TokenEndpoint: http://waste-obligations-wiremock/oauth2/v2.0/token
      PrnCommonBackend__BaseAddress: http://waste-obligations-wiremock/
      WasteOrganisations__BaseAddress: http://waste-obligations-wiremock/
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health/all']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - cdp-tenant

################################################################################

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
