server {
  listen 80;

  location = /manage-recycling-obligations {
    return 308 /manage-recycling-obligations/;
  }

  location /manage-recycling-obligations/ {
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Prefix /manage-recycling-obligations;

    rewrite ^/manage-recycling-obligations/(.*)$ /$1 break;
    proxy_pass http://waste-obligations-frontend:3000;
  }
}
