name: Journey Tests

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Publish']
    types: [completed]

jobs:
  tests:
    strategy:
      max-parallel: 1
      matrix:
        profile: [e2e, accessibility, security]
    uses: DEFRA/waste-obligations-journey-tests/.github/workflows/journey-tests.yml@main
    with: { profile: ${{ matrix.profile }} }
    secrets: inherit
