name: Publish Hot Fix

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: CDP-build-hotfix-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0 # Depth 0 is required for branch-based versioning
      - name: Test code and Create Test Coverage Reports
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: |
          npm ci
          npm run build:frontend
          npm run format:check
          npm run lint
          npm test

      - name: Test translation tooling
        run: |
          npm run translations:install
          npm run test:translations
          npm --prefix scripts/translations run audit

      - name: Security audit
        run: npm run security-audit

      - name: Test Docker Image Build
        run: |
          set +e
          docker build --no-cache --tag cdp-node-frontend-template .
          exit $?

  publish:
    name: Publish hot fix
    needs: [build, sonarcloud-scan]
    runs-on: ubuntu-latest
    permissions:
      contents: write # Create the release tag.
      id-token: write # Authenticate to AWS using OIDC.
    env:
      AWS_REGION: eu-west-2
      AWS_ACCOUNT_ID: '094954420758'
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # Depth 0 is required for branch-based versioning
      - name: Publish Hot Fix
        uses: DEFRA/cdp-build-action/build-hotfix@dfb527d1bca7591fbbfd32ac007557745e888cf2 # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  sonarcloud-scan:
    name: CDP SonarCloud Scan
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
