name: Run SonarCloud coverage scan

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: CDP SonarCloud coverage scan
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Build and create test coverage reports
        run: |
          npm ci
          npm run build:frontend
          npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@1a6d90ebcb0e6a6b1d87e37ba693fe453195ae25 # v5.3.1 #  (or check latest version on https://github.com/marketplace/actions/official-sonarqube-scan)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
