name: Run SonarCloud coverage scan

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: CDP SonarCloud coverage scan
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Build and create test coverage reports
        run: |
          npm ci
          npm run build:frontend
          npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@ba9859eae8dd6bd29e412f25ddbbef3d032000f4 # v5.3.1 #  (or check latest version on https://github.com/marketplace/actions/official-sonarqube-scan)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
